jobs:
  build:
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    strategy:
      matrix:
        java:
        - '11'
        scala:
        - 2.12.10
        - 2.13.1
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - with:
        java-version: ${{ matrix.java }}
      uses: actions/setup-java@v1
    - run: |
        echo "::set-env name=current_week::$(( $(date +%U) ))"
        echo "::set-env name=last_week::$(( $(date +%U) - 1 ))"
      name: Get current week
    - with:
        path: ~/.cache/coursier
        key: coursier-${{ env.current_week }}
        restore-keys: coursier-${{ env.last_week }}
      uses: actions/cache@v1
      name: Cache SBT coursier cache
    - with:
        path: ~/.sbt
        key: sbt-${{ env.current_week }}
        restore-keys: sbt-${{ env.last_week }}
      uses: actions/cache@v1
      name: Cache SBT
    - run: sbt -client ++$SCALA_VERSION clean
      name: Start SBT Server
    - run: sbt -client ++$SCALA_VERSION test
      name: Tests
    - run: sbt -client ++$SCALA_VERSION doc
      name: Scaladocs
    - run: sbt -client ++$SCALA_VERSION mimaReportBinaryIssues
      name: MiMa
    - run: sbt -client ++$SCALA_VERSION scalafmtCheckAll
      name: Scalafmt
    - if: startsWith(matrix.scala, '2.12')
      run: sbt -client ++$SCALA_VERSION docs/makeSite
      name: Test docs
    - run: sbt -client ++$SCALA_VERSION shutdown
      name: Stop SBT Server
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
name: CI
'on':
- push
- pull_request
