jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check generated YAML files
      run: sbt convertDhall\n[[ $(git status --porcelain | wc -l) -eq 0 ]]\n
name: Check Dhall configs
'on':
- push
- pull_request
