jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Generate YAML files
      run: sbt convertDhall
    - name: Check for differences
      run: '[[ $(git status --porcelain | wc -l) -eq 0 ]]'
name: Check Dhall configs
'on':
- push
- pull_request
